services:
  postgres:
    container_name: pg-instance-test
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "secret1"
    ports:
      - "5431:5431"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "ryendaltsev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "secret1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

